// These are substrings which if discovered in the URL should be flagged for closer investigation
// primarily as it might indicate bad intent on the part of the requester
var susURLs = [
    "1=1",
    "3x=3x",
    "admin",
    "alfa",
    "alfindex",
    "author=",
    "backoffice",
    "backup",
    "biif",
	"bypass",
    "config",
    "credentials",
    "daksldlkdsadas",
    "database",
    "download",
    "evil.php",
    "githubusercontent",
    "ghost=send",
    "gutsevich",
	"h4ck",
	"hack",
    "install",
    "login",
    "owa",
    "passwd",
    "password",
    "phpinfo",
    "phpmyadmin",
    "pma",
	"symbpass",
	"t2rghf.jpg",
    "upload",
    "wlwmanifest",
    "wso.php",
    "wwwroot",
    "xmlrpc",
    "\%20",
    ".env",
    ".sql",
    "1ogin",
];
module.exports = {susURLs}