// These are substrings which if discovered in the URL should be flagged for closer investigation, as it might indicate bad intent on the part of the requester
// You could also include where people are searching for a software package you don't use
// For example - if your website is not in WordPress/Drupal/Joomla/etc, then any attempts to access associated files would be suspect in your environment.
var susURLs = [
    "1=1",
    "3x=3x",
    "admin",
    "alfa",
    "alfindex",
    "author=",
    "backoffice",
    "backup",
	"bala=up",
	"beence",
    "biif",
	"bypass",
	"byp4ss",
    "config",
    "credentials",
    "d3wl7",
    "daksldlkdsadas",
    "database",
    "download",
    "evil.php",
    "githubusercontent",
    "ghost=send",
    "gutsevich",
	"h4ck",
	"hack",
    "install",
    "login",
	"NmRtJOUjAdutReQj/scRjKUhleBpzmTyO",
    "owa",
    "passwd",
    "password",
    "phpinfo",
    "phpmyadmin",
	"phpshells",
    "pma",
	"symbpass",
	"t2rghf.jpg",
    "upload",
    "wlwmanifest",
	"writetofile",
    "wso.php",
	"wsoshell",
    "wwwroot",
    "xmlrpc",
	"xploit",
    "\%20",
	"\%2A",
    ".env",
    ".sql",
    "1ogin",
];
module.exports = {susURLs}